CREATE TABLE [dbo].[Customers](
	[CustomerID] [varchar](11) NOT NULL,
	[EDICustomerID] [varchar](20) NULL,
	[Company] [varchar](40) NULL,
	[Address1] [varchar](35) NULL,
	[Address2] [varchar](35) NULL,
	[City] [varchar](35) NULL,
	[State] [varchar](10) NULL,
	[ZIP] [varchar](10) NULL,
	[Country] [varchar](30) NULL,
	[Phone1] [varchar](20) NULL,
	[Phone2] [varchar](20) NULL,
	[Fax] [varchar](20) NULL,
	[Email] [varchar](512) NULL,
	[URL] [varchar](30) NULL,
	[Status] [char](1) NOT NULL,
	[CustomerType] [char](1) NOT NULL,
	[Category] [tinyint] NULL,
	[Class] [int] NULL,
	[Region] [tinyint] NULL,
	[Date] [datetime] NOT NULL,
	[UPSAccountID] [varchar](20) NULL,
	[ShipVia] [varchar](6) NOT NULL,
	[Comment] [varchar](2000) NULL,
	[SaleType] [varchar](3) NOT NULL,
	[PriceCategory] [tinyint] NULL,
	[PaymentTerm] [tinyint] NULL,
	[SalesDiscount] [real] NULL CONSTRAINT [DF_Customers_SalesDiscount]  DEFAULT (0),
	[ServiceCharges] [money] NULL CONSTRAINT [DF_Customers_ServiceCharges]  DEFAULT (0),
	[DropShipOnly] [bit] NOT NULL CONSTRAINT [DF_Customers_DropShipOnly]  DEFAULT (0),
	[SpecialPricing] [bit] NOT NULL CONSTRAINT [DF_Customers_SpecialPricing]  DEFAULT (0),
	[SpecialDescription] [bit] NOT NULL CONSTRAINT [DF_Customers_SpecialDescription]  DEFAULT (0),
	[LoadPrice] [char](1) NOT NULL,
	[LoadPercentage] [real] NULL CONSTRAINT [DF_Customers_LoadPercentage]  DEFAULT (0),
	[TaxRate] [real] NULL,
	[TaxID] [varchar](3) NULL,
	[CustomerTaxID] [varchar](20) NULL,
	[ARCAccount] [varchar](20) NOT NULL,
	[STLAccount] [varchar](20) NOT NULL,
	[FCRAccount] [varchar](20) NOT NULL,
	[DRVAccount] [varchar](20) NOT NULL,
	[CreditLimit] [money] NOT NULL CONSTRAINT [DF_Customers_CreditLimit]  DEFAULT (0),
	[OpenCredit] [money] NOT NULL CONSTRAINT [DF_Customers_OpenCredit]  DEFAULT (0),
	[CurrentBalance] [money] NOT NULL CONSTRAINT [DF_Customers_CurrentBalance]  DEFAULT (0),
	[ConsignmentLimit] [money] NOT NULL CONSTRAINT [DF_Customers_ConsignmentLimit]  DEFAULT (0),
	[ConsignmentBalance] [money] NOT NULL CONSTRAINT [DF_Customers_ConsignmentBalance]  DEFAULT (0),
	[CPCOBalance] [money] NOT NULL CONSTRAINT [DF_Customers_CPCOBalance]  DEFAULT (0),
	[CPROBalance] [money] NOT NULL CONSTRAINT [DF_Customers_CPROBalance]  DEFAULT (0),
	[OpenSO] [money] NOT NULL CONSTRAINT [DF_Customers_OpenSO]  DEFAULT (0),
	[PTD_Sales] [money] NOT NULL CONSTRAINT [DF_Customers_PTD_Sales]  DEFAULT (0),
	[YTD_Sales] [money] NOT NULL CONSTRAINT [DF_Customers_YTD_Sales]  DEFAULT (0),
	[YTD_Orders] [money] NOT NULL CONSTRAINT [DF_Customers_YTD_Orders]  DEFAULT (0),
	[YTD_Payments] [money] NOT NULL CONSTRAINT [DF_Customers_YTD_Payments]  DEFAULT (0),
	[YTD_Credits] [money] NOT NULL CONSTRAINT [DF_Customers_YTD_Credits]  DEFAULT (0),
	[YTD_Adjustments] [money] NOT NULL CONSTRAINT [DF_Customers_YTD_Adjustments]  DEFAULT (0),
	[YTD_Discounts] [money] NOT NULL CONSTRAINT [DF_Customers_YTD_Discounts]  DEFAULT (0),
	[YTD_Consignments] [money] NOT NULL CONSTRAINT [DF_Customers_YTD_Consignment]  DEFAULT (0),
	[LastInvoiceDate] [datetime] NULL,
	[LastInvoiceAmount] [money] NOT NULL CONSTRAINT [DF_Customers_LastInvoiceAmount]  DEFAULT (0),
	[LastOrderDate] [datetime] NULL,
	[LastOrderAmount] [money] NOT NULL CONSTRAINT [DF_Customers_LastOrderAmount]  DEFAULT (0),
	[LastPaymentDate] [datetime] NULL,
	[LastPaymentAmount] [money] NOT NULL CONSTRAINT [DF_Customers_LastPaymentAmount]  DEFAULT (0),
	[LastCreditAmount] [money] NOT NULL CONSTRAINT [DF_Customers_LastCredit]  DEFAULT (0),
	[LastCreditDate] [datetime] NULL,
	[MCE_Allowed] [bit] NOT NULL CONSTRAINT [DF_Customers_MCE_Allowed]  DEFAULT (0),
	[ASN_Process] [bit] NOT NULL CONSTRAINT [DF_Customers_ASN_Process]  DEFAULT (0),
	[COD] [bit] NOT NULL CONSTRAINT [DF_Customers_COD]  DEFAULT (0),
	[Freight_Collect] [bit] NOT NULL CONSTRAINT [DF_Customers_Freight_Collect]  DEFAULT (0),
	[OneItemPerBale] [bit] NOT NULL CONSTRAINT [DF_Customers_One_Item_Per_Bale]  DEFAULT (0),
	[Print_EDI_Invoice] [bit] NOT NULL CONSTRAINT [DF_Customers_PrintEDIInvoice]  DEFAULT (0),
	[ProcessEDIInbound] [bit] NOT NULL CONSTRAINT [DF_Customers_ProcessEDIInbound]  DEFAULT (0),
	[Process_810_Doc] [bit] NOT NULL CONSTRAINT [DF_Customers_Process_810_Doc]  DEFAULT (0),
	[Special_Lables] [bit] NOT NULL CONSTRAINT [DF_Customers_SpecialLables]  DEFAULT (0),
	[AccountsSum] [money] NOT NULL CONSTRAINT [DF_Customers_AccountsSum]  DEFAULT (0),
	[TotalMerchandize] [money] NOT NULL CONSTRAINT [DF_Customers_TotalMerchandize]  DEFAULT (0),
	[ADDUser] [smallint] NOT NULL,
	[ADDDate] [datetime] NOT NULL,
	[MODUser] [smallint] NULL,
	[MODDate] [datetime] NULL,
	[PrintUCC128Labels] [bit] NOT NULL CONSTRAINT [DF_Customers_PrintUCC128Labels]  DEFAULT (0),
	[SDQAddress] [char](1) NULL,
	[OldCustomerCode] [varchar](50) NULL,
	[PastDuePercentage] [tinyint] NOT NULL CONSTRAINT [DF_Customers_PastDuePercentage]  DEFAULT (0),
	[PriceFormat] [char](1) NOT NULL,
	[UniqueSpecialID] [bit] NOT NULL CONSTRAINT [DF_Customers_UniqueSpecialID]  DEFAULT (1),
	[CustomerVendorCode] [varchar](15) NULL,
	[EDIPrice] [bit] NOT NULL CONSTRAINT [DF_Customers_PricePriority]  DEFAULT (0),
	[CommissionSet] [varchar](6) NULL,
	[SeparateFreightCharges] [bit] NOT NULL CONSTRAINT [DF_Customers_SeperateFreightCharges]  DEFAULT (0),
	[AllowDuplicatePOinDS] [bit] NOT NULL CONSTRAINT [DF_Customers_AllowDuplicatePOinDS]  DEFAULT (0),
	[RemoveFromMail] [bit] NOT NULL CONSTRAINT [DF_Customers_RemoveFromMail]  DEFAULT (0),
	[StockingChargesType] [char](1) NULL,
	[StockingChargesValue] [money] NULL CONSTRAINT [DF_Customers_StockingChargesValue]  DEFAULT (0),
	[OverLookLimitChecks] [bit] NULL,
	[WEBCustomer] [bit] NULL,
	[Remarks] [varchar](2000) NULL,
	[Generate_ASN] [bit] NULL CONSTRAINT [DF_Customers_Generate_ASN]  DEFAULT (0),
	[DefaultShippingPriority] [tinyint] NOT NULL CONSTRAINT [DfltDefaultShippingPriority]  DEFAULT (1),
	[NotSendCongAck] [varchar](1) NULL,
	[ExcludeFromRecall] [varchar](1) NULL,
	[InsuranceSuppliedDate] [datetime] NULL,
	[UCC_SSDate] [datetime] NULL,
	[UCC_CCDate] [datetime] NULL,
	[MTADate] [datetime] NULL,
	[ApplyFinanceCharges] [varchar](1) NULL,
	[FinanceCharges] [real] NULL,
	[ExcludeFromSigning] [char](1) NOT NULL CONSTRAINT [DF__Customers__Exclu__7644C4CF]  DEFAULT ('N'),
	[OrderAcknowledgement] [tinyint] NULL,
	[ShipmentNotification] [tinyint] NULL,
	[OrderAcknowledgementEmail] [varchar](60) NULL,
	[ShipmentNotificationEmail] [varchar](60) NULL,
	[GenerateEDIUPS] [char](1) NOT NULL DEFAULT ('N'),
	[Signature_Required_forDelivery] [char](1) NULL,
	[UPSShipmentNotification] [char](1) NULL DEFAULT ('N'),
	[UPSNotificationRecepient] [varchar](60) NULL,
	[OrderAcknowledgementCcEmail] [varchar](60) NULL,
	[ShipmentNotificationCcEmail] [varchar](60) NULL,
	[UPSNotificationRecepient2] [varchar](60) NULL DEFAULT (''),
	[LastName] [varchar](40) NULL,
	[DoNot_MergePO] [varchar](1) NULL,
	[EDI_Export832] [bit] NULL,
	[EDI_Export846] [bit] NULL,
	[EDI_Export870] [bit] NULL,
	[Generate_ASN_Lowes] [bit] NULL,
	[EDI_Export855] [bit] NULL,
	[Residential] [varchar](1) NULL,
	[FreightPrepaid] [varchar](1) NULL,
	[ShipperID] [varchar](20) NULL,
	[EDI_Export812] [bit] NULL,
	[FileFormat] [char](1) NULL,
	[IgnorePriceChecks] [char](1) NULL DEFAULT ('N'),
	[ShipComplete] [varchar](1) NULL,
	[HomeNumber] [varchar](20) NULL,
	[CellNumber] [varchar](20) NULL,
	[WorkNumber] [varchar](20) NULL,
	[DonotApplyAutoWhs] [varchar](1) NULL,
	[AllowOnlyCustStyleItem] [varchar](1) NULL,
	[AllowToPlaceOrder] [varchar](1) NULL,
	[Override_Shipvia] [varchar](1) NULL,
	[UPS_Shipvia] [varchar](6) NULL,
	[UPS_StartingWeight] [real] NULL,
	[UPS_EndingWeight] [real] NULL,
	[Fedex_Shipvia] [varchar](6) NULL,
	[Fedex_StartingWeight] [real] NULL,
	[Fedex_EndingWeight] [real] NULL,
	[InvoiceNotification] [tinyint] NULL,
	[InvoiceNotification_Email1] [varchar](60) NULL,
	[InvoiceNotification_Email2] [varchar](60) NULL,
	[InvoiceNotification_Email3] [varchar](60) NULL,
	[InvoiceNotification_Email4] [varchar](60) NULL,
	[InvoiceNotification_Email5] [varchar](60) NULL,
	[ProcessEDI850FromWHS] [varchar](1) NULL,
	[Other_ShipVia] [varchar](6) NULL,
	[Other_ShipVia_StartingWeight] [real] NULL,
	[Other_ShipVia_EndingWeight] [real] NULL,
	[EDIPriceConflict] [bit] NULL,
	[PriorityEDI850FromWHS] [varchar](1) NULL,
	[Cust_WarehouseID] [varchar](3) NULL,
	[EDI_810SWHS] [varchar](3) NULL,
	[GenerateGTIN14Labels] [varchar](1) NULL,
	[PackagePackingSlip] [int] NULL,
	[ETA_Split] [char](1) NULL,
	[AllowVoidBaleOnShipComplete] [varchar](1) NULL,
	[Process_856_Doc] [bit] NULL,
	[SendETAInInventryFeed] [bit] NULL,
	[CustomerComments] [varchar](max) NULL,
	[UserNo] [int] NULL,
	[ExcludeInventroryProjection] [bit] NULL,
	[AllowAutoBilling] [bit] NULL,
	[Process_856S_Doc] [bit] NULL,
	[AllowWarehouseChangePktVoid] [bit] NULL,
	[Process_852_Doc] [bit] NULL,
	[InventoryDaysEDI846] [int] NULL,
	[SpecialPriceVariance] [real] NULL DEFAULT ((0)),
	[Process_856P_Doc] [bit] NULL,
	[AllowSingleWHS] [varchar](1) NULL,
	[ProcessEDI850WHSJumping] [varchar](1) NULL,
	[UPS_Shipvia_NR] [varchar](6) NULL,
	[UPS_StartingWeight_NR] [real] NULL,
	[UPS_EndingWeight_NR] [real] NULL,
	[FedEx_Shipvia_NR] [varchar](6) NULL,
	[FedEx_StartingWeight_NR] [real] NULL,
	[FedEx_EndingWeight_NR] [real] NULL,
	[Other_ShipVia_NR] [varchar](6) NULL,
	[Other_ShipVia_StartingWeight_NR] [real] NULL,
	[Other_ShipVia_EndingWeight_NR] [real] NULL,
	[UPSNotificationRecepient3] [varchar](60) NULL,
	[UPSNotificationRecepient4] [varchar](60) NULL,
	[UPSNotificationRecepient5] [varchar](60) NULL,
	[DeclareVlaueAmount] [money] NULL,
	[TestMode] [varchar](1) NULL,
	[ShowSizeInMeters] [tinyint] NULL,
	[DoNotPrintInvoice] [varchar](1) NULL,
	[DoNotPrintCredits] [varchar](1) NULL,
	[DoNotPrintDebits] [varchar](1) NULL,
	[DoNotPrintCreditMemo] [varchar](1) NULL,
	[DoNotPrintConsignment] [varchar](1) NULL,
	[DoNotPrintMEStatement] [varchar](1) NULL,
	[DoNotPrintConsignmentReturn] [varchar](1) NULL,
	[IncludeDeclareValue] [varchar](1) NULL,
	[ExclProDiscount] [varchar](1) NULL,
	[DoNotUseForRepZio] [varchar](1) NULL,
	[Automatic_NotShipable] [bit] NULL,
	[Export_832] [bit] NULL,
	[AllowB2BPromotionalDiscount] [varchar](1) NULL,
	[EDI_Export180] [bit] NULL,
	[SkipPrinting] [bit] NULL,
	[ShippingCharges] [decimal](14, 2) NULL,
	[AllowExpandedLabel] [bit] NULL,
	[DeclareValueAmount] [decimal](18, 0) NULL,
	[BillingWithTracking] [varchar](1) NULL,
	[LCFP] [varchar](1) NULL,
	[RDCSoperOrder] [varchar](1) NULL,
	[ShowPackingSlipOnInvoices] [varchar](1) NULL,
	[WebSite] [char](1) NULL,
	[Province] [varchar](30) NULL,
	[AllowOnlyCustB2B] [bit] NULL,
	[CcSecCode] [varchar](4) NULL,
	[CcNumber] [varchar](20) NULL,
	[B2BOrderPlacement] [char](1) NULL,
	[DiscFromDate] [date] NULL,
	[DiscToDate] [date] NULL,
	[HideSales] [char](1) NULL,
	[Generate_ASN_DC] [bit] NULL,
	[BuyerName] [varchar](50) NULL,
	[PayableContactName] [varchar](50) NULL,
	[PayableContactPhone] [varchar](20) NULL,
	[PayableEmail] [varchar](100) NULL,
	[BuyerEmail] [varchar](100) NULL,
	[EDI_846SplitFile] [char](1) NULL,
	[RugCustomer] [char](1) NULL,
	[BroadloomCustomer] [char](1) NULL,
	[PreShipmentDays] [int] NULL,
	[InvoiceAfterTrailerClosed] [varchar](1) NULL DEFAULT ('N'),
	[UPS_MinLength] [real] NULL,
	[UPS_MaxLength] [real] NULL,
	[UPS_MinWidth] [real] NULL,
	[UPS_MaxWidth] [real] NULL,
	[Fedex_MinLength] [real] NULL,
	[Fedex_MaxLength] [real] NULL,
	[Fedex_MinWidth] [real] NULL,
	[Fedex_MaxWidth] [real] NULL,
	[Other_ShipVia_MinLength] [real] NULL,
	[Other_ShipVia_MaxLength] [real] NULL,
	[Other_ShipVia_MinWidth] [real] NULL,
	[Other_ShipVia_MaxWidth] [real] NULL,
	[WeightLevel4_Rugs_ShipVia] [varchar](6) NULL,
	[WeightLevel4_Rugs_MinWeight] [real] NULL,
	[WeightLevel4_Rugs_MaxWeight] [real] NULL,
	[WeightLevel4_Rugs_MinLength] [real] NULL,
	[WeightLevel4_Rugs_MaxLength] [real] NULL,
	[WeightLevel4_Rugs_MinWidth] [real] NULL,
	[WeightLevel4_Rugs_MaxWidth] [real] NULL,
	[UPS_ShipVia_NR_MinLength] [real] NULL,
	[UPS_ShipVia_NR_MaxLength] [real] NULL,
	[UPS_ShipVia_NR_MinWidth] [real] NULL,
	[UPS_ShipVia_NR_Maxwidth] [real] NULL,
	[Fedex_ShipVia_NR_MinLength] [real] NULL,
	[Fedex_ShipVia_NR_MaxLength] [real] NULL,
	[Fedex_ShipVia_NR_MinWidth] [real] NULL,
	[Fedex_ShipVia_NR_MaxWidth] [real] NULL,
	[Other_ShipVia_NR_MinLength] [real] NULL,
	[Other_ShipVia_NR_MaxLength] [real] NULL,
	[Other_ShipVia_NR_MinWidth] [real] NULL,
	[Other_ShipVia_NR_MaxWidth] [real] NULL,
	[WeightLevel4_NRugs_ShipVia] [varchar](6) NULL,
	[WeightLevel4_NRugs_MinWeight] [real] NULL,
	[WeightLevel4_NRugs_MaxWeight] [real] NULL,
	[WeightLevel4_NRugs_MinLength] [real] NULL,
	[WeightLevel4_NRugs_MaxLength] [real] NULL,
	[WeightLevel4_NRugs_MinWidth] [real] NULL,
	[WeightLevel4_NRugs_MaxWidth] [real] NULL,
	[ChangeWHSOnBORelease] [bit] NULL,
	[UPS_MinGirth] [real] NULL,
	[UPS_MaxGirth] [real] NULL,
	[Fedex_MinGirth] [real] NULL,
	[Fedex_MaxGirth] [real] NULL,
	[Other_ShipVia_MinGirth] [real] NULL,
	[Other_ShipVia_MaxGirth] [real] NULL,
	[WeightLevel4_Rugs_MinGirth] [real] NULL,
	[WeightLevel4_Rugs_MaxGirth] [real] NULL,
	[UPS_ShipVia_NR_MinGirth] [real] NULL,
	[UPS_ShipVia_NR_MaxGirth] [real] NULL,
	[Fedex_ShipVia_NR_MinGirth] [real] NULL,
	[Fedex_ShipVia_NR_MaxGirth] [real] NULL,
	[Other_ShipVia_NR_MinGirth] [real] NULL,
	[Other_ShipVia_NR_MaxGirth] [real] NULL,
	[WeightLevel4_NRugs_MinGirth] [real] NULL,
	[WeightLevel4_NRugs_MaxGirth] [real] NULL,
	[AllowAutomatedBORelease] [bit] NULL,
	[Process_856C_Doc] [bit] NULL,
	[GTIN_Starting_Digit] [varchar](1) NULL,
	[OverRideShipViaForWeight] [bit] NULL,
	[Cancel_EDI_SOLine] [bit] NULL,
	[Process_945_Doc] [bit] NULL,
	[IsProcess_856DBM] [bit] NULL,
	[IsProcess_810DBM] [bit] NULL,
	[IsProcess_855DBM] [bit] NULL,
	[IsProcess_856CDBM] [bit] NULL,
	[ExternalID] [varchar](30) NULL,
	[ConflictWithoutPriortiy] [bit] NULL,
	[DoNotApplyEDIDiscount] [bit] NULL,
	[ExcludeInventoryBufferInEDI] [bit] NULL,
	[WeekAdjustmentDays] [int] NULL,
	[DoNotVerifyAddress] [bit] NULL,
	[NotShippableOnPSVoid] [bit] NULL,
	[Process_865_Doc] [bit] NULL,
	[AddFreightFromSO] [bit] NULL DEFAULT ((0)),
	[EnforceTaxRate] [bit] NOT NULL DEFAULT ((0)),
	[Process_EDI_TMS] [bit] NULL,
	[AddShippingChargesFromCS] [bit] NULL,
	[PaymentMode] [char](1) NULL,
	[EnableOneStepShipment] [bit] NULL,
	[AllowInternationalOrders] [bit] NULL,
	[AllowLowCostSelling] [bit] NULL,
	[AddSpecialProgItem] [bit] NULL,
	[UseSubCompany] [char](1) NULL,
	[CancelBOLineOfEDI] [bit] NULL,
	[Generate810StoreWise] [bit] NULL,
	[AllowReservePartialLine] [bit] NULL,
	[GenerateBillofLadingASN] [bit] NULL,
	[ParentCustomerID] [varchar](11) NULL,
	[ParentBit] [bit] NULL,
	[ReviewShipments] [bit] NULL DEFAULT ((0)),
	[ShipViaOverride] [nvarchar](25) NULL CONSTRAINT [DF_Customers_ShipViaOverride]  DEFAULT ('Girth'),
	[ShippingChargesType] [varchar](1) NULL,
	[UseATSFromHoldOrders] [bit] NULL,
	[ExcludeBOQtyInETA] [bit] NULL,
	[PrintPSFromSpooler] [bit] NULL,
	[RateSamples] [bit] NULL DEFAULT ((0)),
	[AllowEmptyEta] [bit] NULL DEFAULT ((0)),
	[EtaNDays] [int] NULL,
	[MakeSingleInvoice] [bit] NULL DEFAULT ((0)),
	[AllowBackOrderOnDiscontinuedItem] [bit] NULL,
	[PriceConflictNonEDI] [bit] NULL,
	[CancelEDISO] [bit] NULL,
	[RestrictShipViaOnLineWHSChange] [bit] NULL DEFAULT ((0)),
	[SendEDI855Cancellation] [bit] NULL,
	[SendEDI855Updates] [bit] NULL,
	[ExcludeDiscItemsin846] [bit] NULL,
	[OpenCashReceiptAmount] [money] NULL,
	[PersonalDataMasking] [bit] NULL,
	[DaysToMaskDataAfterOrderCompletion] [int] NULL,
	[RetentionPolicyRemarks] [varchar](4000) NULL,
	[UseWhiteLabelInEDI] [bit] NULL DEFAULT ((0)),
	[CancelLineOnVoidBale] [bit] NULL,
	[ApproveDataMasking] [bit] NULL,
	[EnableUOMCAConversion] [bit] NULL,
	[ReSendEDI855Updates] [bit] NULL,
	[UseCustomerInstructionAsSpecialInstruction] [bit] NULL,
	[EnableAutoBatchGeneration] [bit] NULL,
	[UseCustomerUPCInEDI] [bit] NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY NONCLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_Category] FOREIGN KEY([Category])
REFERENCES [dbo].[Category] ([CategoryNo])
GO

ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_Category]
GO

ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_Class] FOREIGN KEY([Class])
REFERENCES [dbo].[Class] ([ClassNo])
GO

ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_Class]
GO

ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_PaymentMode] FOREIGN KEY([PaymentMode])
REFERENCES [dbo].[PaymentModes] ([PaymentCode])
GO

ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_PaymentMode]
GO

ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_PaymentTerms] FOREIGN KEY([PaymentTerm])
REFERENCES [dbo].[PaymentTerms] ([PaymentTermNo])
GO

ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_PaymentTerms]
GO

ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_PriceCategories] FOREIGN KEY([PriceCategory])
REFERENCES [dbo].[PriceCategories] ([CategoryNo])
GO

ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_PriceCategories]
GO

ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_ShipVia] FOREIGN KEY([ShipVia])
REFERENCES [dbo].[ShipVia] ([ShipViaID])
GO

ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_ShipVia]
GO

ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_TaxRates] FOREIGN KEY([TaxID])
REFERENCES [dbo].[TaxRates] ([TaxID])
GO

ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_TaxRates]
GO


